apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  labels:
    k8s-app: nginx-ingress
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113
  selector:
    app: nginx-ingress
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: nginx-ingress
  name: nginx-ingress
  namespace: nginx-ingress
subsets:
- addresses:
  - ip: 192.168.20.31 # change to your kube-controller-manager ip
  - ip: 192.168.20.30 # change to your kube-controller-manager ip
  ports:
  - name: metrics
    port: 9113
    protocol: TCP
